namespace Advent2016;

public partial class Day14 : Advent.Day
{
    /*
        *  Description -    Input is an initial key for a key generation routine.  Keys are generated by hashing the input plus an increasing counter.
        *                   A key is valid if it contains the same character 3 times in a row and the same character 5 times in a row in the following 1000 keys.
        *  
        *  Part 1 -        What is the counter of the first valid key?
        *  Part 2 -        As part 1, but when generating a key, each hash should be performed on its own output 2016 times
    */
    public Day14(bool testMode, int whichPart, string input) : base(testMode, whichPart, input)
    {
        switch (WhichPart, TestMode)
        {
            case (1, true):
                Inputs.Add("abc");
                Expecteds.Add("22728");
                break;
            case (1, false):
                Inputs.Add("yjdafjpo");
                Expecteds.Add("25427");
                break;
            case (2, true):
                Inputs.Add("abc");
                Expecteds.Add("22551");
                break;
            case (2, false):
                Inputs.Add("yjdafjpo");
                Expecteds.Add("22045");
                break;
        }
    }
}
